baseURL: https://sjoeboo.github.io/
languageCode: en-us
title: "Hi there"
theme: PaperMod
label:
  text: "Home"
  icon: /apple-touch-icon.png
  iconHeight: 35

params:
  profileMode:
    enabled: true
    title: "Hello. I'm Matt." # optional default will be site title
    subtitle: "Senior SRE, Dad, and more"
